# Generated by Django 5.2.17 on 2026-09-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelversion',
            name='minio_uri',
        ),
    ]
