# Generated by Django 5.2.17 on 2026-09-17 09:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_type', models.CharField(max_length=100)),
                ('mlflow_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField()),
                ('architecture', models.CharField(blank=True, max_length=100)),
                ('accuracy', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('is_deployable', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('deployment_points', models.JSONField(default=list)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_format', models.CharField(max_length=20)),
                ('file_size', models.PositiveBigIntegerField()),
                ('minio_uri', models.CharField(blank=True, max_length=500)),
                ('run_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('logical_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='registry.logicalmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
