# Generated by Django 5.2.17 on 2026-09-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_remove_modelversion_minio_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalmodel',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='model_artifact_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
