# Generated by Django 5.2.17 on 2026-09-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_logicalmodel_purpose_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modelversion',
            constraint=models.UniqueConstraint(fields=('logical_model', 'version_number'), name='unique_logical_model_version'),
        ),
    ]
